// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package erc20

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "erc20"
	ScDescription = "ERC-20 PoC for IOTA Smart Contracts"
	HScName       = wasmlib.ScHname(0x200e3733)
)

const (
	ParamAccount = "ac"
	ParamAmount  = "amount"
	ParamOwner   = "o"
	ParamSupply  = "s"
	ParamTo      = "to"
)

const (
	ResultAmount = "amount"
	ResultSupply = "s"
)

const (
	StateBalances = "b"
	StateOwner    = "owner"
	StateSupply   = "s"
)

const (
	FuncInit        = "init"
	FuncMint        = "mint"
	FuncTransfer    = "transfer"
	ViewBalanceOf   = "balanceOf"
	ViewTotalSupply = "totalSupply"
)

const (
	HFuncInit        = wasmlib.ScHname(0x1f44d644)
	HFuncMint        = wasmlib.ScHname(0xa29addcf)
	HFuncTransfer    = wasmlib.ScHname(0xa15da184)
	HViewBalanceOf   = wasmlib.ScHname(0x67ef8df4)
	HViewTotalSupply = wasmlib.ScHname(0x9505e6ca)
)
