// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package erc20

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "erc20"
	ScDescription = "ERC-20 PoC for IOTA Smart Contracts"
	HScName       = wasmlib.ScHname(0x200e3733)
)

const (
	ParamAccount    = wasmlib.Key("ac")
	ParamAmount     = wasmlib.Key("amount")
	ParamDelegation = wasmlib.Key("d")
	ParamOwner      = wasmlib.Key("o")
	ParamRecipient  = wasmlib.Key("r")
	ParamSupply     = wasmlib.Key("s")
	ParamTo         = wasmlib.Key("to")
)

const (
	ResultAmount   = wasmlib.Key("amount")
	ResultDecimals = wasmlib.Key("decimals")
	ResultName     = wasmlib.Key("name")
	ResultSupply   = wasmlib.Key("s")
	ResultSymbol   = wasmlib.Key("symbol")
)

const (
	StateAllowances = wasmlib.Key("a")
	StateBalances   = wasmlib.Key("b")
	StateDecimals   = wasmlib.Key("decimals")
	StateName       = wasmlib.Key("name")
	StateOwner      = wasmlib.Key("owner")
	StateSupply     = wasmlib.Key("s")
	StateSymbol     = wasmlib.Key("symbol")
)

const (
	FuncApprove      = "approve"
	FuncInit         = "init"
	FuncMint         = "mint"
	FuncTransfer     = "transfer"
	FuncTransferFrom = "transferFrom"
	ViewAllowance    = "allowance"
	ViewBalanceOf    = "balanceOf"
	ViewDecimals     = "decimals"
	ViewName         = "name"
	ViewSymbol       = "symbol"
	ViewTotalSupply  = "totalSupply"
)

const (
	HFuncApprove      = wasmlib.ScHname(0xa0661268)
	HFuncInit         = wasmlib.ScHname(0x1f44d644)
	HFuncMint         = wasmlib.ScHname(0xa29addcf)
	HFuncTransfer     = wasmlib.ScHname(0xa15da184)
	HFuncTransferFrom = wasmlib.ScHname(0xd5e0a602)
	HViewAllowance    = wasmlib.ScHname(0x5e16006a)
	HViewBalanceOf    = wasmlib.ScHname(0x67ef8df4)
	HViewDecimals     = wasmlib.ScHname(0x879dc081)
	HViewName         = wasmlib.ScHname(0x0df7da3a)
	HViewSymbol       = wasmlib.ScHname(0x3e93d19b)
	HViewTotalSupply  = wasmlib.ScHname(0x9505e6ca)
)
