// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package erc20

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAccount    = 0
	IdxParamAmount     = 1
	IdxParamDelegation = 2
	IdxParamOwner      = 3
	IdxParamRecipient  = 4
	IdxParamSupply     = 5
	IdxParamTo         = 6
	IdxResultAmount    = 7
	IdxResultSupply    = 8
	IdxStateAllowances = 9
	IdxStateBalances   = 10
	IdxStateOwner      = 11
	IdxStateSupply     = 12
)

const keyMapLen = 13

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAccount,
	ParamAmount,
	ParamDelegation,
	ParamOwner,
	ParamRecipient,
	ParamSupply,
	ParamTo,
	ResultAmount,
	ResultSupply,
	StateAllowances,
	StateBalances,
	StateOwner,
	StateSupply,
}

var idxMap [keyMapLen]wasmlib.Key32
