// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package erc20

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAccount    = 0
	IdxParamAmount     = 1
	IdxParamDelegation = 2
	IdxParamName       = 3
	IdxParamOwner      = 4
	IdxParamRecipient  = 5
	IdxParamSupply     = 6
	IdxParamSymbol     = 7
	IdxParamTo         = 8
	IdxResultAmount    = 9
	IdxResultDecimals  = 10
	IdxResultName      = 11
	IdxResultSupply    = 12
	IdxResultSymbol    = 13
	IdxStateAllowances = 14
	IdxStateBalances   = 15
	IdxStateDecimals   = 16
	IdxStateName       = 17
	IdxStateOwner      = 18
	IdxStateSupply     = 19
	IdxStateSymbol     = 20
)

const keyMapLen = 21

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAccount,
	ParamAmount,
	ParamDelegation,
	ParamName,
	ParamOwner,
	ParamRecipient,
	ParamSupply,
	ParamSymbol,
	ParamTo,
	ResultAmount,
	ResultDecimals,
	ResultName,
	ResultSupply,
	ResultSymbol,
	StateAllowances,
	StateBalances,
	StateDecimals,
	StateName,
	StateOwner,
	StateSupply,
	StateSymbol,
}

var idxMap [keyMapLen]wasmlib.Key32
