// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package erc20

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAccount    = 0
	IdxParamAmount     = 1
	IdxParamDelegation = 2
	IdxParamOwner      = 3
	IdxParamRecipient  = 4
	IdxParamSupply     = 5
	IdxParamTo         = 6
	IdxResultAmount    = 7
	IdxResultDecimals  = 8
	IdxResultName      = 9
	IdxResultSupply    = 10
	IdxResultSymbol    = 11
	IdxStateAllowances = 12
	IdxStateBalances   = 13
	IdxStateDecimals   = 14
	IdxStateName       = 15
	IdxStateOwner      = 16
	IdxStateSupply     = 17
	IdxStateSymbol     = 18
)

const keyMapLen = 19

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAccount,
	ParamAmount,
	ParamDelegation,
	ParamOwner,
	ParamRecipient,
	ParamSupply,
	ParamTo,
	ResultAmount,
	ResultDecimals,
	ResultName,
	ResultSupply,
	ResultSymbol,
	StateAllowances,
	StateBalances,
	StateDecimals,
	StateName,
	StateOwner,
	StateSupply,
	StateSymbol,
}

var idxMap [keyMapLen]wasmlib.Key32
