name: CrowdSale
description: CrowdSale description
structs: {}
typedefs: {}
state:
  owner: AgentID // current owner of this smart contract
  balances: map[AgentID]Int64 // balances per account
  supply: Int64 // total supply of the token
funcs:
  init:
    params:
      owner: AgentID? // optional owner of this smart contract
      supply: Int64 // initial token supply
      token: Color // IEXP token color
  setOwner:
    access: owner // current owner of this smart contract
    params:
      owner: AgentID // new owner of this smart contract
  transfer:
    params:
      account: AgentID // target account
      amount: Int64 // amount of tokens to transfer
  transferFrom:
    params:
      account=: AgentID // sender account
      amount: Int64 // amount of tokens to transfer
      recipient: AgentID // recipient account
views:
  getOwner:
    results:
      owner: AgentID // current owner of this smart contract
  balanceOf:
    params:
      account: AgentID // sender account
    results:
      amount: Int64
  totalSupply:
    results:
      supply: Int64
