// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package crowdsale

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "crowdsale"
	ScDescription = "CrowdSale description"
	HScName       = wasmlib.ScHname(0x0da82426)
)

const ParamOwner = wasmlib.Key("owner")

const ResultOwner = wasmlib.Key("owner")

const StateOwner = wasmlib.Key("owner")

const (
	FuncInit     = "init"
	FuncSetOwner = "setOwner"
	ViewGetOwner = "getOwner"
)

const (
	HFuncInit     = wasmlib.ScHname(0x1f44d644)
	HFuncSetOwner = wasmlib.ScHname(0x2a15fe7b)
	HViewGetOwner = wasmlib.ScHname(0x137107a6)
)
